### ISSUE TITLE
Events not firing if directive have an ID attribute

### ISSUE THREAD

**Issue by asaf050** [angular-ui/ui-leaflet-draw#10]
Hey,

All events are not working if leaflet directive have an ID attribute.
Here's an example fiddle of the bug:

http://jsfiddle.net/6hxffegq/15/

How can I solve it?

**Comment by josephbisaillon** [comment]
If you are still looking for the solution to this. You just need to name it in the event handler string. 

` $scope.$on('leafletDirectiveDraw.map.' + eventName, function(e, payload) {`

` $scope.$on('leafletDirectiveDraw.YOURMAPIDHERE.' + eventName, function(e, payload) {`

**Comment by nmccready** [comment]
@tallented can you post your work around to this problem.

**Comment by nmccready** [comment]
apologies this is actually now fixed in 0.0.5
