### ISSUE TITLE
Touch click is not supported when drawing

### ISSUE THREAD

**Issue by AnasELMALEKI** [angular-ui/ui-leaflet-draw#11]
I use ui leaflet draw in a hybrid app developped using ionic, when I test in a local server on the computer's browser it works fine, but when I build the apk, install it on an andrid device, it doesn't work.

**Comment by nmccready** [comment]
I would hit up the (leaflet-draw)[https://github.com/angular-ui/ui-leaflet-draw/blob/master/package.json#L16] fork that we're pointing to; or override the prototypes for the lower libraries to set the correct listeners.

This is more than likely not specific to ui-leaflet-draw.
