### ISSUE TITLE
IE10/11 Unknown touch event error

### ISSUE THREAD

**Issue by biosflasher** [angular-ui/ui-leaflet-draw#5]
On IE10 and 11 the map fails to load with following error:

Unknown touch event type <div class="angular-leaflet-map ng-isolate-scope leaflet-container leaflet-touch leaflet-fade-anim" style="width: 100%; height: 480px; position: relative;" width="100%" height="480px" lf-draw="map.drawOptions" lf-center="map.center">

Steps to reproduce:
Open http://angular-ui.github.io/ui-leaflet-draw/ in IE10/11

Since it works in regular Leaflet.draw I believe its an issue with ui-leaflet-draw

**Comment by mikeyc7m** [comment]
i've hit this issue too, everything was working fine until recently.

**Comment by nmccready** [comment]
Is it ui-leaflet-draw or is it leaflet-draw itself? All the events and touch are handled by leaflet-draw. Take it up to them and then I'll bump the version.

**Comment by alexkb** [comment]
@nmccready I think it's something to do with ui-leaflet-draw. If you look at the [Leaflet.draw demo](http://leaflet.github.io/Leaflet.draw/) in IE11, it renders and works fine.

**Comment by alexkb** [comment]
There's another thread about this issue by @micahiverson over in Leaflet/Leaflet#4168. It's a bit hacky, but simply calling the existing addPointerListernEnd() function on these IE events, seems to fix things for me in IE11:

	addPointerListener: function (obj, type, handler, id) {

		switch (type) {
		case 'touchstart':
			return this.addPointerListenerStart(obj, type, handler, id);
		case 'touchend':
			return this.addPointerListenerEnd(obj, type, handler, id);
		case 'touchmove':
			return this.addPointerListenerMove(obj, type, handler, id);
		case 'touchcancel':
			return this.addPointerListenerEnd(obj, type, handler, id);
		case 'touchleave':
			return this.addPointerListenerEnd(obj, type, handler, id);
		default:
			throw 'Unknown touch event type';
		}
	},

**Comment by alexkb** [comment]
I've just upgraded from leaflet-draw 0.2.4 to 0.3.0 and the previous "Unknown touch event" error seems to have been fixed without the need for the addPointerListener touch events hack above.

**Comment by AnasELMALEKI** [comment]
@alexkb I use ui leaflet draw in a hybrid app developped using ionic, when I test in a local server on the computer's browser it works fine, but when I build the apk, install it on an andrid device, it doesn't work.

**Comment by nmccready** [comment]
@AnasELMALEKI open a separate issue with an example for this. Closing due to @alexkb comment
