### ISSUE TITLE
Is it possible to get Control Obj?

### ISSUE THREAD

**Issue by jfsebastian** [angular-ui/ui-leaflet-draw#7]
Hi;

I'm trying to activate Leatlet.draw from an external button (using this approach http://stackoverflow.com/questions/15775103/leaflet-draw-mapping-how-to-initiate-the-draw-function-without-toolbar ) and I can't find how to get control object.

Is it even possible?

Thanks, and regards from Spain

**EDITED!!**

I've just realized that the example is just using the options. So it shouldn't be needed the whole object, but just in case I leave the question just in case it could be useful for anybody.

**Comment by ValentinH** [comment]
@jfsebastian I'm not sure to understand with your edit: did you manage to toggle the draw from an external button? If yes, would you mind sharing a small indication about how you achieve this, please? :)

**Comment by nmccready** [comment]
He means you set the callback handle to get the control on the leaflet-draw options itself in the scope. However there is a bug with these two lines.

https://github.com/angular-ui/ui-leaflet-draw/blob/master/src/drawDirective.coffee#L47-L48

```
      if options.control?.promises?
        options.control.promised _deferred.promise
```

Where they should both be `promised` or `promises`. But in reality it should probably just be `options.control` and `option.control(_deferred.promise)`.


As far as options setup in scope @jfsebastian means:

```
  // Setup the options for the circle -> Override icons, immediately editable
  options = {
    control: {
        promised: function (promise) {
        }
    }
    stroke: true,
    color: '#333333',
    opacity: 1.0,
    weight: 4,
    fillColor: '#FFFFFF',
    moveIcon: centerIcon,
    resizeIcon: new L.Icon({
      iconUrl: '/assets/radius_handle_18px.png',
      iconSize: [12, 12],
      iconAnchor: [0,0]
    })
  }
```

**Comment by ValentinH** [comment]
Hum I'm not sure to understand, then if I want to toggle manually the control (like when the user clicks the icon), I would do `promise.enable()`?

**Comment by nmccready** [comment]
```
  options = {
    control: {
        promised: function (promise) {
          promise.then function (control) {  control.enable()}
        }
    }
```

**Comment by ValentinH** [comment]
OK so the promise will be resolved on map load?

**Comment by nmccready** [comment]
The promise will be resolved when it is finished being hooked up to the map.

**Comment by ValentinH** [comment]
OK thanks for your help :)

**Comment by nmccready** [comment]
I think this is resolved. Closing
