### ISSUE TITLE
Possibly issue with uglify

### ISSUE THREAD

**Issue by petermanger** [angular-ui/ui-leaflet-draw#8]
I appear to encounter an issue with the directive being lost (I get a message no such provider lfDrawDirective) as part of (gulp)uglification.  I have narrowed it down to ui-leaflet-draw I think - but have not tested anything specific other than it only seems to happen with uglify on.

Posting in case others encounter something similar or can shed more light or might help hint solution to why the draw controls disappear after (gulp)building.

**Comment by joshkopecek** [comment]
I get the same problem. I think this is linked to issue #9 

I solved by setting `mangle: false` in the Uglify options, but this defeats (some) of the purpose of using Uglify.

There's some issue with the annotations not working with this, but I can't see what the problem is at the moment.

**Comment by nmccready** [comment]
Fixed w this commit ea39f79ba14a980344060647b9a638a86de07ca3

**Comment by nmccready** [comment]
apologies this is actually now fixed in 0.0.5
